---
title: 'Preprocessing: HSP English'
author: "author"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")
```


```{r}
read.pcibex <- function(filepath, auto.colnames=TRUE, fun.col=function(col,cols){cols[cols==col]<-paste(col,"Ibex",sep=".");return(cols)}) {
  n.cols <- max(count.fields(filepath,sep=",",quote=NULL),na.rm=TRUE)
  if (auto.colnames){
    cols <- c()
    con <- file(filepath, "r")
    while ( TRUE ) {
      line <- readLines(con, n = 1, warn=FALSE)
      if ( length(line) == 0) {
        break
      }
      m <- regmatches(line,regexec("^# (\\d+)\\. (.+)\\.$",line))[[1]]
      if (length(m) == 3) {
        index <- as.numeric(m[2])
        value <- m[3]
        if (is.function(fun.col)){
         cols <- fun.col(value,cols)
        }
        cols[index] <- value
        if (index == n.cols){
          break
        }
      }
    }
    close(con)
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=cols))
  }
  else{
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=seq(1:n.cols)))
  }
}

# Read in the results
d <- read.pcibex("../data/results_null.csv")
length(unique(d$MD5.hash.of.participant.s.IP.address))

names(d)

```


# Add necessary columns

```{r}
# This may need to be changed if we want to lok the prolific ids
d <- d %>%
  mutate(Participant = match(MD5.hash.of.participant.s.IP.address, unique(MD5.hash.of.participant.s.IP.address))) %>%
  # Remove potentially identifying information
  select(-MD5.hash.of.participant.s.IP.address)


# Add a Response column# Add a Response column
d$Response <- ""
d$Response <- ifelse(d$Parameter == "Selection", d$Value, d$Response)
# remove all strings after '_' 
d$Response <- unlist(strsplit(d$Response, split='_', fixed=TRUE))[1]

# Create the Accuracy column checking if Response is a substring of target
d$Response <- as.character(d$Response)
d$Accuracy <- mapply(function(response, pattern) {
  ifelse(grepl(response, pattern), 1, 0)
}, d$Response, d$target)

# Split the factors column into multiple columns
d[c("Verb","Force","Comp")] <- str_split_fixed(d$factors,'-',3)

# Subset to only test items 
d_test <- d %>% 
  # keep all test trials (Label contains the substring "test_")
    filter(grepl("test_",Label)) %>%
    dplyr::select(Participant),Verb,Force,Comp,factors,Response,Accuracy)

# Write to .csv
write.csv(d_test,"../../data/test_processed.csv")

```

```{r}
d_indef <- d %>% 
    filter(Label == "filler_article") %>%
    dplyr::select(Participant,Verb,Force,Comp,factors,Response,Accuracy) %>%
    # filter out cases where "Response" has no value
    filter(Response != "" ) 
# Write to .csv
write.csv(d_indef,"../../data/indef_processed.csv")

d_action <- d %>% 
    filter(Label == "filler_action") %>%
    dplyr::select(Participant,Verb,Force,Comp,factors,Response,Accuracy) %>%
    # filter out cases where "Response" has no value
    filter(Response != "" ) 
# Write to .csv
write.csv(d_indef,"../../data/action_processed.csv")
```


